version: "3.8"

services:
  nextjs_prod:
    # image:
    env_file: .env.prod
    build:
      context: .
      # dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    image: nextjs_prod
    environment:
      - NODE_ENV=production
