version: "3.8"

services:
  nextjs_dev:
    # image:
    env_file: .env.dev
    build:
      context: .
      # dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
